#!/bin/bash

##############
# Properties #
##############

###########
# Methods #
###########

function help_get_message() {

  # Getting input args
  this_help_message="$1"

  # Logging debug info
  log_print debug "Getting help message for: $this_help_message"

  # Getting message
  help_print_"${this_help_message}"

  # Exiting always as 0 after help messages
  exit 0
}

function help_print_inbox() {
  printf "${color_bold}${system_long_name} - Inbox${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  The place to capture your ideas.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} inbox ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add ${color_blue}ITEM_NAME${color_reset}\n"
  printf "  clarify\n"
  printf "  delete ${color_blue}ITEM_ID${color_reset}\n"
  printf "  list\n"
  printf "\n"
}

function help_print_inbox_add() {
  printf "${color_bold}${system_long_name} - Inbox Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add items to the inbox.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} inbox add ${color_blue}ITEM_NAME${color_reset}\n"
  printf "\n"
  printf "${color_bold}ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}ITEM_NAME  ${color_gray}Item or idea to add to inbox${color_reset}\n"
  printf "\n"
}

function help_print_inbox_delete() {
  printf "${color_bold}${system_long_name} - Inbox Delete${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Removes items from the inbox.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} inbox delete ${color_blue}ITEM_ID${color_reset}\n"
  printf "\n"
  printf "${color_bold}ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}ITEM_ID  ${color_gray}ID of inbox item to delete${color_reset}\n"
  printf "\n"
}
function help_print_main() {
  printf "${color_bold}${system_long_name} - Help${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  A ${color_underline}life planner${color_reset} tool to use without leaving the terminal.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS] ${color_red}<COMMAND> ${color_green}[SUBCOMMAND] ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}GLOBAL ARGUMENTS:${color_reset}\n"
  printf "  debug            ${color_gray}Enable debug messages${color_reset}\n"
  printf "  nocolor          ${color_gray}Disable colors in terminal${color_reset}\n"
  printf "  noprompt         ${color_gray}Skip user prompts${color_reset}\n"
  printf "\n"
  printf "${color_bold}SYSTEM COMMANDS:${color_reset}\n"
  printf "  help             ${color_gray}This help message${color_reset}\n"
  printf "  install          ${color_gray}Installs this CLI to /usr/local/bin/plan${color_reset}\n"
  printf "  search ${color_blue}PATTERN${color_reset}   ${color_gray}Search across all entities${color_reset}\n"
  printf "  version          ${color_gray}Get CLI version${color_reset}\n"
  printf "\n"
  printf "${color_bold}WORKFLOW COMMANDS:${color_reset}\n"
  printf "  capture ${color_blue}IDEA${color_reset}     ${color_gray}1. Capture ideas to the inbox${color_reset}\n"
  printf "  clarify          ${color_gray}2. Clarify inbox items into objects${color_reset}\n"
  printf "  organize ${color_blue}LEVEL${color_reset}   ${color_gray}3. View items organized by horizon${color_reset}\n"
  printf "  reflect          ${color_gray}4. Review horizons for updates${color_reset}\n"
  printf "  engage           ${color_gray}5. What to work on now${color_reset}\n"
  printf "\n"
  printf "${color_bold}OBJECT COMMANDS:${color_reset}\n"
  printf "  inbox            ${color_gray}Manage inbox items (Ground)${color_reset}\n"
  printf "  task             ${color_gray}Manage next actions (Ground)${color_reset}\n"
  printf "  recurring        ${color_gray}Manage recurring tasks (Ground)${color_reset}\n"
  printf "  habit            ${color_gray}Manage habits (Ground)${color_reset}\n"
  printf "  collection       ${color_gray}Manage collections (Ground)${color_reset}\n"
  printf "  item             ${color_gray}Manage collection items (Ground)${color_reset}\n"
  printf "  project          ${color_gray}Manage projects (Horizon 1)${color_reset}\n"
  printf "  area             ${color_gray}Manage areas of responsibility (Horizon 2)${color_reset}\n"
  printf "  goal             ${color_gray}Manage goals (Horizon 3)${color_reset}\n"
  printf "  vision           ${color_gray}Manage visions (Horizon 4)${color_reset}\n"
  printf "  purpose          ${color_gray}Manage life purposes (Horizon 5)${color_reset}\n"
  printf "  principle        ${color_gray}Manage guiding principles (Horizon 5)${color_reset}\n"
  printf "\n"
}

function help_print_area() {
  printf "${color_bold}${system_long_name} - Area${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage areas of responsibility (GTD Horizon 2).\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} area ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add ${color_blue}AREA_NAME [ARGS]${color_reset}\n"
  printf "  delete ${color_blue}AREA_NAME${color_reset}\n"
  printf "  edit ${color_blue}AREA_NAME [ARGS]${color_reset}\n"
  printf "  list\n"
  printf "\n"
}

function help_print_area_add() {
  printf "${color_bold}${system_long_name} - Area Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new area of responsibility.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} area add ${color_blue}AREA_NAME [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}AREA_NAME                   ${color_gray}Name of the area${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --description ${color_blue}DESC          ${color_gray}Description of the area${color_reset}\n"
  printf "\n"
}

function help_print_area_delete() {
  printf "${color_bold}${system_long_name} - Area Delete${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Delete an area of responsibility.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} area delete ${color_blue}AREA_NAME${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}AREA_NAME                   ${color_gray}Name of the area to delete${color_reset}\n"
  printf "\n"
}

function help_print_area_edit() {
  printf "${color_bold}${system_long_name} - Area Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing area of responsibility.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} area edit ${color_blue}AREA_NAME [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}AREA_NAME                   ${color_gray}Name of the area to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name        ${color_blue}NEW_NAME      ${color_gray}New name for the area${color_reset}\n"
  printf "  --description ${color_blue}DESC          ${color_gray}New description for the area${color_reset}\n"
  printf "\n"
}

function help_print_task() {
  printf "${color_bold}${system_long_name} - Task${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage tasks (next actions).\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} task ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add ${color_blue}TASK_NAME [ARGS]${color_reset}\n"
  printf "  complete ${color_blue}TASK_ID${color_reset}\n"
  printf "  delete ${color_blue}TASK_ID${color_reset}\n"
  printf "  edit ${color_blue}TASK_ID${color_reset}\n"
  printf "  list     ${color_blue}[--status STATUS]${color_reset}\n"
  printf "  search   ${color_blue}PATTERN${color_reset}\n"
  printf "  start    ${color_blue}TASK_ID${color_reset}\n"
  printf "  stop     ${color_blue}TASK_ID${color_reset}\n"
  printf "\n"
}

function help_print_task_list() {
  printf "${color_bold}${system_long_name} - Task List${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  List tasks, optionally filtered by status.\n"
  printf "  By default, shows all tasks that are not Done.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} task list ${color_blue}[--status STATUS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --status ${color_blue}STATUS  ${color_gray}Filter by status (default: Pending and In Progress)${color_reset}\n"
  printf "\n"
  printf "${color_bold}STATUS VALUES:${color_reset}\n"
  printf "  Pending      ${color_gray}Show only pending tasks${color_reset}\n"
  printf "  In Progress  ${color_gray}Show only tasks currently in progress${color_reset}\n"
  printf "  Done         ${color_gray}Show only completed tasks${color_reset}\n"
  printf "  all          ${color_gray}Show all tasks regardless of status${color_reset}\n"
  printf "\n"
}

function help_print_task_add() {
  printf "${color_bold}${system_long_name} - Task Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add items to the task list.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} task add ${color_blue}TASK_NAME [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}TASK_NAME                   ${color_gray}Name or description${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --start-date ${color_blue}YYYY-MM-DD     ${color_gray}When task is able to be done${color_reset}\n"
  printf "  --due-date   ${color_blue}YYYY-MM-DD     ${color_gray}Deadline${color_reset}\n"
  printf "  --project    ${color_blue}PROJECT_NAME   ${color_gray}Related project${color_reset}\n"
  printf "\n"
}

function help_print_project() {
  printf "${color_bold}${system_long_name} - Project${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage projects (GTD Horizon 1).\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} project ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add      ${color_blue}PROJECT_NAME [ARGS]${color_reset}\n"
  printf "  complete ${color_blue}PROJECT_ID${color_reset}\n"
  printf "  delete   ${color_blue}PROJECT_ID${color_reset}\n"
  printf "  edit     ${color_blue}PROJECT_ID [ARGS]${color_reset}\n"
  printf "  list     ${color_blue}[--status STATUS]${color_reset}\n"
  printf "  search   ${color_blue}PATTERN${color_reset}\n"
  printf "  start    ${color_blue}PROJECT_ID${color_reset}\n"
  printf "  stop     ${color_blue}PROJECT_ID${color_reset}\n"
  printf "\n"
}

function help_print_project_list() {
  printf "${color_bold}${system_long_name} - Project List${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  List projects, optionally filtered by status.\n"
  printf "  By default, shows all projects that are not Done.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} project list ${color_blue}[--status STATUS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --status ${color_blue}STATUS  ${color_gray}Filter by status (default: Pending and In Progress)${color_reset}\n"
  printf "\n"
  printf "${color_bold}STATUS VALUES:${color_reset}\n"
  printf "  Pending      ${color_gray}Show only pending projects${color_reset}\n"
  printf "  In Progress  ${color_gray}Show only projects currently in progress${color_reset}\n"
  printf "  Done         ${color_gray}Show only completed projects${color_reset}\n"
  printf "  all          ${color_gray}Show all projects regardless of status${color_reset}\n"
  printf "\n"
}

function help_print_goal() {
  printf "${color_bold}${system_long_name} - Goal${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage goals (GTD Horizon 3).\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} goal ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add      ${color_blue}GOAL_NAME [ARGS]${color_reset}\n"
  printf "  complete ${color_blue}GOAL_ID${color_reset}\n"
  printf "  delete   ${color_blue}GOAL_ID${color_reset}\n"
  printf "  edit     ${color_blue}GOAL_ID [ARGS]${color_reset}\n"
  printf "  list     ${color_blue}[--status STATUS]${color_reset}\n"
  printf "  search   ${color_blue}PATTERN${color_reset}\n"
  printf "  start    ${color_blue}GOAL_ID${color_reset}\n"
  printf "  stop     ${color_blue}GOAL_ID${color_reset}\n"
  printf "\n"
}

function help_print_goal_list() {
  printf "${color_bold}${system_long_name} - Goal List${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  List goals, optionally filtered by status.\n"
  printf "  By default, shows all goals that are not Done.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} goal list ${color_blue}[--status STATUS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --status ${color_blue}STATUS  ${color_gray}Filter by status (default: Pending and In Progress)${color_reset}\n"
  printf "\n"
  printf "${color_bold}STATUS VALUES:${color_reset}\n"
  printf "  Pending      ${color_gray}Show only pending goals${color_reset}\n"
  printf "  In Progress  ${color_gray}Show only goals currently in progress${color_reset}\n"
  printf "  Done         ${color_gray}Show only completed goals${color_reset}\n"
  printf "  all          ${color_gray}Show all goals regardless of status${color_reset}\n"
  printf "\n"
}

function help_print_goal_add() {
  printf "${color_bold}${system_long_name} - Goal Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new goal.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} goal add ${color_blue}GOAL_NAME${color_reset} --area ${color_blue}AREA_NAME [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}GOAL_NAME                   ${color_gray}Name of the goal${color_reset}\n"
  printf "  --area       ${color_blue}AREA_NAME     ${color_gray}Area this goal belongs to${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --vision     ${color_blue}VISION_NAME   ${color_gray}Vision this goal contributes to${color_reset}\n"
  printf "  --start-date ${color_blue}YYYY-MM-DD    ${color_gray}When the goal starts${color_reset}\n"
  printf "  --due-date   ${color_blue}YYYY-MM-DD    ${color_gray}Deadline for the goal${color_reset}\n"
  printf "\n"
}

function help_print_project_add() {
  printf "${color_bold}${system_long_name} - Project Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new project.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} project add ${color_blue}PROJECT_NAME${color_reset} --area ${color_blue}AREA_NAME [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}PROJECT_NAME                ${color_gray}Name of the project${color_reset}\n"
  printf "  --area       ${color_blue}AREA_NAME     ${color_gray}Area this project belongs to${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --goal       ${color_blue}GOAL_NAME     ${color_gray}Goal this project contributes to${color_reset}\n"
  printf "  --start-date ${color_blue}YYYY-MM-DD    ${color_gray}When the project starts${color_reset}\n"
  printf "  --due-date   ${color_blue}YYYY-MM-DD    ${color_gray}Deadline for the project${color_reset}\n"
  printf "\n"
}

function help_print_task_edit() {
  printf "${color_bold}${system_long_name} - Task Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing task.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} task edit ${color_blue}TASK_ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}TASK_ID                     ${color_gray}ID of the task to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name       ${color_blue}NEW_NAME      ${color_gray}New name for the task${color_reset}\n"
  printf "  --project    ${color_blue}PROJECT_NAME  ${color_gray}Link to a project${color_reset}\n"
  printf "  --start-date ${color_blue}YYYY-MM-DD    ${color_gray}When task is able to be done${color_reset}\n"
  printf "  --due-date   ${color_blue}YYYY-MM-DD    ${color_gray}Deadline${color_reset}\n"
  printf "\n"
}

function help_print_project_edit() {
  printf "${color_bold}${system_long_name} - Project Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing project.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} project edit ${color_blue}PROJECT_ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}PROJECT_ID                  ${color_gray}ID of the project to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name       ${color_blue}NEW_NAME      ${color_gray}New name for the project${color_reset}\n"
  printf "  --area       ${color_blue}AREA_NAME     ${color_gray}Link to an area${color_reset}\n"
  printf "  --goal       ${color_blue}GOAL_NAME     ${color_gray}Link to a goal${color_reset}\n"
  printf "  --start-date ${color_blue}YYYY-MM-DD    ${color_gray}When the project starts${color_reset}\n"
  printf "  --due-date   ${color_blue}YYYY-MM-DD    ${color_gray}Deadline for the project${color_reset}\n"
  printf "\n"
}

function help_print_goal_edit() {
  printf "${color_bold}${system_long_name} - Goal Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing goal.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} goal edit ${color_blue}GOAL_ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}GOAL_ID                     ${color_gray}ID of the goal to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name       ${color_blue}NEW_NAME      ${color_gray}New name for the goal${color_reset}\n"
  printf "  --area       ${color_blue}AREA_NAME     ${color_gray}Link to an area${color_reset}\n"
  printf "  --vision     ${color_blue}VISION_NAME   ${color_gray}Link to a vision${color_reset}\n"
  printf "  --start-date ${color_blue}YYYY-MM-DD    ${color_gray}When the goal starts${color_reset}\n"
  printf "  --due-date   ${color_blue}YYYY-MM-DD    ${color_gray}Deadline for the goal${color_reset}\n"
  printf "\n"
}

function help_print_vision() {
  printf "${color_bold}${system_long_name} - Vision${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage visions (GTD Horizon 4).\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} vision ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add      ${color_blue}VISION_NAME [ARGS]${color_reset}\n"
  printf "  complete ${color_blue}VISION_ID${color_reset}\n"
  printf "  delete   ${color_blue}VISION_ID${color_reset}\n"
  printf "  edit     ${color_blue}VISION_ID [ARGS]${color_reset}\n"
  printf "  list     ${color_blue}[--status STATUS]${color_reset}\n"
  printf "  search   ${color_blue}PATTERN${color_reset}\n"
  printf "  start    ${color_blue}VISION_ID${color_reset}\n"
  printf "  stop     ${color_blue}VISION_ID${color_reset}\n"
  printf "\n"
}

function help_print_vision_list() {
  printf "${color_bold}${system_long_name} - Vision List${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  List visions, optionally filtered by status.\n"
  printf "  By default, shows all visions that are not Done.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} vision list ${color_blue}[--status STATUS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --status ${color_blue}STATUS  ${color_gray}Filter by status (default: Pending and In Progress)${color_reset}\n"
  printf "\n"
  printf "${color_bold}STATUS VALUES:${color_reset}\n"
  printf "  Pending      ${color_gray}Show only pending visions${color_reset}\n"
  printf "  In Progress  ${color_gray}Show only visions currently in progress${color_reset}\n"
  printf "  Done         ${color_gray}Show only completed visions${color_reset}\n"
  printf "  all          ${color_gray}Show all visions regardless of status${color_reset}\n"
  printf "\n"
}

function help_print_vision_add() {
  printf "${color_bold}${system_long_name} - Vision Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new vision.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} vision add ${color_blue}VISION_NAME${color_reset} --area ${color_blue}AREA_NAME [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}VISION_NAME                 ${color_gray}Name of the vision${color_reset}\n"
  printf "  --area       ${color_blue}AREA_NAME     ${color_gray}Area this vision belongs to${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --description ${color_blue}DESC         ${color_gray}Description of the vision${color_reset}\n"
  printf "  --start-date ${color_blue}YYYY-MM-DD    ${color_gray}When the vision starts${color_reset}\n"
  printf "  --due-date   ${color_blue}YYYY-MM-DD    ${color_gray}Deadline for the vision${color_reset}\n"
  printf "\n"
}

function help_print_collection() {
  printf "${color_bold}${system_long_name} - Collection${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage collections (e.g., Books, Games, Movies).\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} collection ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add    ${color_blue}COLLECTION_NAME${color_reset}\n"
  printf "  delete ${color_blue}COLLECTION_ID${color_reset}\n"
  printf "  edit   ${color_blue}COLLECTION_ID [ARGS]${color_reset}\n"
  printf "  list\n"
  printf "  search ${color_blue}PATTERN${color_reset}\n"
  printf "\n"
}

function help_print_collection_add() {
  printf "${color_bold}${system_long_name} - Collection Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new collection.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} collection add ${color_blue}COLLECTION_NAME${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}COLLECTION_NAME             ${color_gray}Name of the collection${color_reset}\n"
  printf "\n"
}

function help_print_collection_edit() {
  printf "${color_bold}${system_long_name} - Collection Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing collection.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} collection edit ${color_blue}COLLECTION_ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}COLLECTION_ID               ${color_gray}ID of the collection to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name ${color_blue}NEW_NAME              ${color_gray}New name for the collection${color_reset}\n"
  printf "\n"
}

function help_print_item() {
  printf "${color_bold}${system_long_name} - Item${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage collection items.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} item ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add      ${color_blue}ITEM_NAME${color_reset} --collection ${color_blue}COLLECTION_NAME${color_reset}\n"
  printf "  complete ${color_blue}ITEM_ID${color_reset}\n"
  printf "  delete   ${color_blue}ITEM_ID${color_reset}\n"
  printf "  edit     ${color_blue}ITEM_ID [ARGS]${color_reset}\n"
  printf "  list     ${color_blue}[--collection COLLECTION_NAME] [--status STATUS]${color_reset}\n"
  printf "  search   ${color_blue}PATTERN${color_reset}\n"
  printf "  start    ${color_blue}ITEM_ID${color_reset}\n"
  printf "  stop     ${color_blue}ITEM_ID${color_reset}\n"
  printf "\n"
}

function help_print_item_add() {
  printf "${color_bold}${system_long_name} - Item Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new item to a collection.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} item add ${color_blue}ITEM_NAME${color_reset} --collection ${color_blue}COLLECTION_NAME${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}ITEM_NAME                   ${color_gray}Name of the item${color_reset}\n"
  printf "  --collection ${color_blue}COLLECTION_NAME ${color_gray}Collection this item belongs to${color_reset}\n"
  printf "\n"
}

function help_print_item_edit() {
  printf "${color_bold}${system_long_name} - Item Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing collection item.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} item edit ${color_blue}ITEM_ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}ITEM_ID                     ${color_gray}ID of the item to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name       ${color_blue}NEW_NAME      ${color_gray}New name for the item${color_reset}\n"
  printf "  --collection ${color_blue}COLLECTION    ${color_gray}Move to different collection${color_reset}\n"
  printf "\n"
}

function help_print_item_list() {
  printf "${color_bold}${system_long_name} - Item List${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  List collection items, optionally filtered by collection and/or status.\n"
  printf "  By default, shows all items that are not Done.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} item list ${color_blue}[--collection COLLECTION_NAME] [--status STATUS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --collection ${color_blue}COLLECTION_NAME  ${color_gray}Filter by collection name${color_reset}\n"
  printf "  --status     ${color_blue}STATUS           ${color_gray}Filter by status (default: Pending and In Progress)${color_reset}\n"
  printf "\n"
  printf "${color_bold}STATUS VALUES:${color_reset}\n"
  printf "  Pending      ${color_gray}Show only pending items${color_reset}\n"
  printf "  In Progress  ${color_gray}Show only items currently in progress${color_reset}\n"
  printf "  Done         ${color_gray}Show only completed items${color_reset}\n"
  printf "  all          ${color_gray}Show all items regardless of status${color_reset}\n"
  printf "\n"
}

function help_print_habit() {
  printf "${color_bold}${system_long_name} - Habit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage habits.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} habit ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add      ${color_blue}NAME${color_reset} --recurrence ${color_blue}FREQUENCY${color_reset}\n"
  printf "  complete ${color_blue}ID${color_reset}\n"
  printf "  delete   ${color_blue}ID${color_reset}\n"
  printf "  edit     ${color_blue}ID [ARGS]${color_reset}\n"
  printf "  list     ${color_blue}[--status STATUS]${color_reset}\n"
  printf "  search   ${color_blue}PATTERN${color_reset}\n"
  printf "\n"
  printf "${color_bold}FREQUENCIES:${color_reset}\n"
  printf "  daily, weekly, monthly, quarterly, biannual, yearly\n"
  printf "\n"
}

function help_print_habit_list() {
  printf "${color_bold}${system_long_name} - Habit List${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  List habits, optionally filtered by status.\n"
  printf "  By default, shows all habits that are not Done.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} habit list ${color_blue}[--status STATUS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --status ${color_blue}STATUS  ${color_gray}Filter by status (default: Pending and In Progress)${color_reset}\n"
  printf "\n"
  printf "${color_bold}STATUS VALUES:${color_reset}\n"
  printf "  Pending      ${color_gray}Show only pending habits${color_reset}\n"
  printf "  In Progress  ${color_gray}Show only habits currently in progress${color_reset}\n"
  printf "  Done         ${color_gray}Show only completed habits${color_reset}\n"
  printf "  all          ${color_gray}Show all habits regardless of status${color_reset}\n"
  printf "\n"
}

function help_print_habit_add() {
  printf "${color_bold}${system_long_name} - Habit Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new habit.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} habit add ${color_blue}NAME${color_reset} --recurrence ${color_blue}FREQUENCY${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}NAME                        ${color_gray}Name of the habit${color_reset}\n"
  printf "  --recurrence ${color_blue}FREQUENCY     ${color_gray}How often (daily/weekly/monthly/quarterly/biannual/yearly)${color_reset}\n"
  printf "\n"
}

function help_print_habit_edit() {
  printf "${color_bold}${system_long_name} - Habit Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing habit.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} habit edit ${color_blue}ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}ID                          ${color_gray}ID of the habit to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name       ${color_blue}NEW_NAME      ${color_gray}New name${color_reset}\n"
  printf "  --recurrence ${color_blue}FREQUENCY     ${color_gray}New frequency${color_reset}\n"
  printf "\n"
}

function help_print_recurring() {
  printf "${color_bold}${system_long_name} - Recurring${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage recurring tasks.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} recurring ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add      ${color_blue}NAME${color_reset} --recurrence ${color_blue}FREQUENCY${color_reset}\n"
  printf "  complete ${color_blue}ID${color_reset}\n"
  printf "  delete   ${color_blue}ID${color_reset}\n"
  printf "  edit     ${color_blue}ID [ARGS]${color_reset}\n"
  printf "  list     ${color_blue}[--status STATUS]${color_reset}\n"
  printf "  search   ${color_blue}PATTERN${color_reset}\n"
  printf "\n"
  printf "${color_bold}FREQUENCIES:${color_reset}\n"
  printf "  daily, weekly, monthly, quarterly, biannual, yearly\n"
  printf "\n"
}

function help_print_recurring_list() {
  printf "${color_bold}${system_long_name} - Recurring List${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  List recurring tasks, optionally filtered by status.\n"
  printf "  By default, shows all recurring tasks that are not Done.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} recurring list ${color_blue}[--status STATUS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --status ${color_blue}STATUS  ${color_gray}Filter by status (default: Pending and In Progress)${color_reset}\n"
  printf "\n"
  printf "${color_bold}STATUS VALUES:${color_reset}\n"
  printf "  Pending      ${color_gray}Show only pending recurring tasks${color_reset}\n"
  printf "  In Progress  ${color_gray}Show only recurring tasks currently in progress${color_reset}\n"
  printf "  Done         ${color_gray}Show only completed recurring tasks${color_reset}\n"
  printf "  all          ${color_gray}Show all recurring tasks regardless of status${color_reset}\n"
  printf "\n"
}

function help_print_recurring_add() {
  printf "${color_bold}${system_long_name} - Recurring Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new recurring task.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} recurring add ${color_blue}NAME${color_reset} --recurrence ${color_blue}FREQUENCY${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}NAME                        ${color_gray}Name of the recurring task${color_reset}\n"
  printf "  --recurrence ${color_blue}FREQUENCY     ${color_gray}How often (daily/weekly/monthly/quarterly/biannual/yearly)${color_reset}\n"
  printf "\n"
}

function help_print_recurring_edit() {
  printf "${color_bold}${system_long_name} - Recurring Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing recurring task.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} recurring edit ${color_blue}ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}ID                          ${color_gray}ID of the recurring task to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name       ${color_blue}NEW_NAME      ${color_gray}New name${color_reset}\n"
  printf "  --recurrence ${color_blue}FREQUENCY     ${color_gray}New frequency${color_reset}\n"
  printf "\n"
}

function help_print_purpose() {
  printf "${color_bold}${system_long_name} - Purpose${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage life purposes (GTD Horizon 5).\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} purpose ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add    ${color_blue}PURPOSE_NAME${color_reset}\n"
  printf "  delete ${color_blue}PURPOSE_ID${color_reset}\n"
  printf "  edit   ${color_blue}PURPOSE_ID [ARGS]${color_reset}\n"
  printf "  list\n"
  printf "  search ${color_blue}PATTERN${color_reset}\n"
  printf "\n"
}

function help_print_purpose_add() {
  printf "${color_bold}${system_long_name} - Purpose Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new life purpose.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} purpose add ${color_blue}PURPOSE_NAME${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}PURPOSE_NAME                ${color_gray}Name of the purpose${color_reset}\n"
  printf "\n"
}

function help_print_purpose_edit() {
  printf "${color_bold}${system_long_name} - Purpose Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing purpose.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} purpose edit ${color_blue}PURPOSE_ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}PURPOSE_ID                  ${color_gray}ID of the purpose to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name ${color_blue}NEW_NAME              ${color_gray}New name for the purpose${color_reset}\n"
  printf "\n"
}

function help_print_principle() {
  printf "${color_bold}${system_long_name} - Principle${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Manage guiding principles (GTD Horizon 5).\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} principle ${color_green}SUBCOMMAND ${color_blue}[ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add    ${color_blue}PRINCIPLE_NAME${color_reset}\n"
  printf "  delete ${color_blue}PRINCIPLE_ID${color_reset}\n"
  printf "  edit   ${color_blue}PRINCIPLE_ID [ARGS]${color_reset}\n"
  printf "  list\n"
  printf "  search ${color_blue}PATTERN${color_reset}\n"
  printf "\n"
}

function help_print_principle_add() {
  printf "${color_bold}${system_long_name} - Principle Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add a new guiding principle.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} principle add ${color_blue}PRINCIPLE_NAME${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}PRINCIPLE_NAME              ${color_gray}Name of the principle${color_reset}\n"
  printf "\n"
}

function help_print_principle_edit() {
  printf "${color_bold}${system_long_name} - Principle Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing principle.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} principle edit ${color_blue}PRINCIPLE_ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}PRINCIPLE_ID                ${color_gray}ID of the principle to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name ${color_blue}NEW_NAME              ${color_gray}New name for the principle${color_reset}\n"
  printf "\n"
}

function help_print_vision_edit() {
  printf "${color_bold}${system_long_name} - Vision Edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Edit an existing vision.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} vision edit ${color_blue}VISION_ID [ARGS]${color_reset}\n"
  printf "\n"
  printf "${color_bold}REQUIRED ARGUMENTS:${color_reset}\n"
  printf "  ${color_blue}VISION_ID                   ${color_gray}ID of the vision to edit${color_reset}\n"
  printf "\n"
  printf "${color_bold}OPTIONAL ARGUMENTS:${color_reset}\n"
  printf "  --name        ${color_blue}NEW_NAME     ${color_gray}New name for the vision${color_reset}\n"
  printf "  --area        ${color_blue}AREA_NAME    ${color_gray}Link to an area${color_reset}\n"
  printf "  --description ${color_blue}DESC         ${color_gray}New description for the vision${color_reset}\n"
  printf "  --start-date  ${color_blue}YYYY-MM-DD   ${color_gray}When the vision starts${color_reset}\n"
  printf "  --due-date    ${color_blue}YYYY-MM-DD   ${color_gray}Deadline for the vision${color_reset}\n"
  printf "\n"
}

#######################
# Workflow Help Pages #
#######################

function help_print_organize() {
  printf "${color_bold}${system_long_name} - Organize${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  View your items organized by GTD horizon.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${system_basename} ${color_gray}[GLOBAL_ARGS]${color_reset} organize ${color_green}LEVEL${color_reset}\n"
  printf "\n"
  printf "${color_bold}LEVELS:${color_reset}\n"
  printf "  ground          ${color_gray}Inbox, Tasks, Recurring, Habits, Collections, Items${color_reset}\n"
  printf "  horizon1 (h1)   ${color_gray}Projects${color_reset}\n"
  printf "  horizon2 (h2)   ${color_gray}Areas of Responsibility${color_reset}\n"
  printf "  horizon3 (h3)   ${color_gray}Goals${color_reset}\n"
  printf "  horizon4 (h4)   ${color_gray}Visions${color_reset}\n"
  printf "  horizon5 (h5)   ${color_gray}Purposes and Principles${color_reset}\n"
  printf "  all             ${color_gray}Everything from ground to horizon 5${color_reset}\n"
  printf "\n"
}
