#!/bin/bash

function help_inbox() {
  log_message debug "Getting help message: inbox"
  printf "${color_bold}${system_banner} - Inbox${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  The place to capture all of your ideas.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${color_underline}${system_basename}${color_reset} ${color_bold}${color_red}inbox ${color_green}SUBCOMMAND${color_reset} ${color_gray}[${color_bold}${color_blue}ARGUMENTS${color_reset}${color_gray}]${color_reset}\n"
  printf "\n"
  printf "${color_bold}SUBCOMMANDS:${color_reset}\n"
  printf "  add\n"
  printf "  clarify\n"
  printf "  delete\n"
  printf "  edit\n"
  printf "  list\n"
  printf "\n"
  exit 0
}

function help_inbox_add() {
  log_message debug "Getting help message: inbox add"
  printf "${color_bold}${system_banner} - Inbox Add${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  Add items to the inbox.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${color_underline}${system_basename}${color_reset} ${color_bold}${color_red}inbox ${color_green}add ${color_blue}ITEM_NAME${color_reset}\n"
  printf "\n"
  printf "${color_bold}ARGUMENTS:${color_reset}\n"
  printf "  ${color_gray}(no supported args)${color_reset}\n"
  printf "\n"
  exit 0
}

function help_main() {
  
  log_message debug "Getting help message: main"
  printf "${color_bold}${system_banner} - Main Help${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  A GTD-inspired task management tool for the terminal.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${color_underline}${system_basename}${color_reset} ${color_bold}${color_red}COMMAND${color_reset} ${color_gray}[${color_bold}${color_green}SUBCOMMAND${color_reset}${color_gray}] [${color_bold}${color_blue}ARGUMENTS${color_reset}${color_gray}]${color_reset}\n"
  printf "\n"
  printf "${color_bold}COMMANDS:${color_reset}\n"
  printf "\n"
  printf "${color_gray}  # Ground #${color_reset}\n"
  printf "  inbox\n"
  printf "  task\n"
  printf "  recurring\n"
  printf "  habit\n"
  printf "  collection\n"
  printf "\n"
  printf "${color_gray}  # Horizon 1 #${color_reset}\n"
  printf "  project\n"
  printf "\n"
  printf "${color_gray}  # Horizon 2 #${color_reset}\n"
  printf "  area\n"
  printf "\n"
  printf "${color_gray}  # Horizon 3 #${color_reset}\n"
  printf "  goal\n"
  printf "\n"
  printf "${color_gray}  # Horizon 4 #${color_reset}\n"
  printf "  vision\n"
  printf "\n"
  printf "${color_gray}  # Horizon 5 #${color_reset}\n"
  printf "  principle\n"
  printf "  purpose\n"
  printf "\n"
  printf "${color_gray}  # GTD Phases #${color_reset}\n"
  printf "  capture\n"
  printf "  clarify\n"
  printf "  organize\n"
  printf "  reflect\n"
  printf "  engage\n"
  printf "\n"
  printf "${color_gray}  # System #${color_reset}\n"
  printf "  help\n"
  printf "  install\n"
  printf "  version\n"
  printf "\n"
  exit 0
}
