#!/bin/bash
system_banner="Lowbit Planner"
system_version="v0.2.0-dev"
system_basename="$(basename $0)"

function system_get_help() {
  
  log_message debug "Getting help message: main"
  printf "${color_bold}${system_banner} - Main Help${color_reset}\n"
  printf "\n"
  printf "${color_bold}DESCRIPTION:${color_reset}\n"
  printf "  A ${color_underline}life planner${color_reset} tool to use without leaving the terminal.\n"
  printf "\n"
  printf "${color_bold}USAGE:${color_reset}\n"
  printf "  ${color_underline}${system_basename}${color_reset} ${color_bold}${color_red}COMMAND${color_reset} ${color_gray}[${color_bold}${color_green}SUBCOMMAND${color_reset}${color_gray}] [${color_bold}${color_blue}ARGUMENTS${color_reset}${color_gray}]${color_reset}\n"
  printf "\n"
  printf "${color_bold}COMMANDS:${color_reset}\n"
  printf "\n"
  printf "${color_gray}  -- Ground --${color_reset}\n"
  printf "  inbox\n"
  printf "  task\n"
  printf "  recurring\n"
  printf "  habit\n"
  printf "  collection\n"
  printf "\n"
  printf "${color_gray}  -- Horizon 1 --${color_reset}\n"
  printf "  project\n"
  printf "\n"
  printf "${color_gray}  -- Horizon 2 --${color_reset}\n"
  printf "  area\n"
  printf "\n"
  printf "${color_gray}  -- Horizon 3 --${color_reset}\n"
  printf "  goal\n"
  printf "\n"
  printf "${color_gray}  -- Horizon 4 --${color_reset}\n"
  printf "  vision\n"
  printf "\n"
  printf "${color_gray}  -- Horizon 5 --${color_reset}\n"
  printf "  principle\n"
  printf "  purpose\n"
  printf "\n"
  printf "${color_gray}  -- Actions --${color_reset}\n"
  printf "  capture\n"
  printf "  clarify\n"
  printf "  organize\n"
  printf "  reflect\n"
  printf "  engage\n"
  printf "\n"
  printf "${color_gray}  -- System --${color_reset}\n"
  printf "  help\n"
  printf "  install\n"
  printf "  version\n"
  printf "\n"
  exit 0
}

function system_get_version() {
  echo "${system_banner} - Version: ${system_version}"
}
